/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package librosfera.vista;

/**
 *
 * @author ornellamesinag.
 */
public class RegistroUsuario extends javax.swing.JPanel {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        labelCreateAccount = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        inputUsername1 = new javax.swing.JTextField();
        inputUsername2 = new javax.swing.JTextField();
        inputUsername3 = new javax.swing.JTextField();
        inputUsername4 = new javax.swing.JTextField();
        inputUsername5 = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(25, 25, 25));
        labelUsername.setText("Registro ");

        inputUsername.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername.setText("Numero de Telefono *");
        inputUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });

        labelCreateAccount.setForeground(new java.awt.Color(25, 25, 25));
        labelCreateAccount.setText("Acepto los terminos y condiciones");

        checkbox1.setLabel("checkbox1");

        inputUsername1.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername1.setText("Nombres");
        inputUsername1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsername1ActionPerformed(evt);
            }
        });

        inputUsername2.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername2.setText("Email *");
        inputUsername2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsername2ActionPerformed(evt);
            }
        });

        inputUsername3.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername3.setText("Apellido Materno");
        inputUsername3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsername3ActionPerformed(evt);
            }
        });

        inputUsername4.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername4.setText("Apellido Paterno");
        inputUsername4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsername4ActionPerformed(evt);
            }
        });

        inputUsername5.setBackground(new java.awt.Color(216, 216, 216));
        inputUsername5.setText("Confirmar Email *");
        inputUsername5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUsername5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsername5ActionPerformed(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(135, 23, 35));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(242, 242, 242));
        buttonLogin.setText("Continuar");
        buttonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });

        labelUsername1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername1.setForeground(new java.awt.Color(25, 25, 25));
        labelUsername1.setText("* campos obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(labelCreateAccount)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(labelUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(inputUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputUsername3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputUsername5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCreateAccount))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsername1ActionPerformed

    private void inputUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsername2ActionPerformed

    private void inputUsername3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsername3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsername3ActionPerformed

    private void inputUsername4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsername4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsername4ActionPerformed

    private void inputUsername5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsername5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsername5ActionPerformed

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked

        // INPUTS //
        String nombreUsuario = inputUsername.getText();
        String claveUsuario = inputPassword.getText();
    }//GEN-LAST:event_buttonLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JTextField inputUsername1;
    private javax.swing.JTextField inputUsername2;
    private javax.swing.JTextField inputUsername3;
    private javax.swing.JTextField inputUsername4;
    private javax.swing.JTextField inputUsername5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCreateAccount;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    // End of variables declaration//GEN-END:variables
}
