/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package librosfera.vista.components;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ateka
 */
public class BookCard extends javax.swing.JPanel {

    /**
     * Creates new form BookCard
     */
    public BookCard(String title, String author) throws IOException {
        initComponents();
        
        /*
        URL imgUrl;
        try {
            imgUrl = new URL("https://covers.openlibrary.org/b/isbn/" + isbn + "-M.jpg");
            BufferedImage image = ImageIO.read(imgUrl);
            this.imgBookCover.setIcon(new ImageIcon(image));
        } catch (MalformedURLException ex) {
            Logger.getLogger(BookCard.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        this.labelAuthor.setText(author);
        this.labelTitle.setText(title);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCover = new javax.swing.JPanel();
        imgBookCover = new javax.swing.JLabel();
        panelBookInfo = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelRate = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelCover.setBackground(new java.awt.Color(255, 204, 204));
        panelCover.setPreferredSize(new java.awt.Dimension(200, 290));
        panelCover.setLayout(new java.awt.BorderLayout());

        imgBookCover.setForeground(new java.awt.Color(0, 0, 0));
        imgBookCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCover.add(imgBookCover, java.awt.BorderLayout.CENTER);

        add(panelCover);

        panelBookInfo.setLayout(new java.awt.GridBagLayout());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitle.setText("Título");
        labelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        panelBookInfo.add(labelTitle, gridBagConstraints);

        labelRate.setText("Puntuación");
        labelRate.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelBookInfo.add(labelRate, gridBagConstraints);

        labelAuthor.setText("Autor");
        labelAuthor.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        panelBookInfo.add(labelAuthor, gridBagConstraints);

        add(panelBookInfo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBookCover;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelRate;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBookInfo;
    private javax.swing.JPanel panelCover;
    // End of variables declaration//GEN-END:variables
}
