/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package librosfera.vista.components;


public class componentNavbar extends javax.swing.JPanel {

    /**
     * Creates new form componentNavbar
     */
    public componentNavbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imgLogo = new javax.swing.JLabel();
        panelNavItems = new javax.swing.JPanel();
        navItemInicio = new javax.swing.JLabel();
        navItemNosotros = new javax.swing.JLabel();
        navItemContacto = new javax.swing.JLabel();
        panelAuthItems = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 80));
        setMinimumSize(new java.awt.Dimension(1400, 80));
        setRequestFocusEnabled(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 32, 0, 32, 0};
        layout.rowHeights = new int[] {0};
        setLayout(layout);

        imgLogo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgLogo.setForeground(new java.awt.Color(255, 0, 0));
        imgLogo.setText("logo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 32, 0, 0);
        add(imgLogo, gridBagConstraints);

        panelNavItems.setBackground(new java.awt.Color(255, 255, 255));
        panelNavItems.setForeground(new java.awt.Color(51, 51, 51));
        panelNavItems.setMaximumSize(new java.awt.Dimension(600, 50));
        panelNavItems.setMinimumSize(new java.awt.Dimension(600, 50));
        panelNavItems.setName(""); // NOI18N
        panelNavItems.setPreferredSize(new java.awt.Dimension(600, 50));
        panelNavItems.setLayout(new java.awt.GridLayout(0, 6));

        navItemInicio.setForeground(new java.awt.Color(51, 51, 51));
        navItemInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navItemInicio.setText("Inicio");
        panelNavItems.add(navItemInicio);

        navItemNosotros.setForeground(new java.awt.Color(51, 51, 51));
        navItemNosotros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navItemNosotros.setText("Nosotros");
        panelNavItems.add(navItemNosotros);

        navItemContacto.setForeground(new java.awt.Color(51, 51, 51));
        navItemContacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navItemContacto.setText("Contacto");
        panelNavItems.add(navItemContacto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(panelNavItems, gridBagConstraints);

        panelAuthItems.setBackground(new java.awt.Color(255, 255, 255));
        panelAuthItems.setForeground(new java.awt.Color(51, 51, 51));
        panelAuthItems.setMaximumSize(new java.awt.Dimension(400, 50));
        panelAuthItems.setMinimumSize(new java.awt.Dimension(400, 50));
        panelAuthItems.setName(""); // NOI18N
        panelAuthItems.setPreferredSize(new java.awt.Dimension(400, 50));
        panelAuthItems.setLayout(new java.awt.GridLayout(0, 4));

        btnLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("Iniciar sesión");
        panelAuthItems.add(btnLogin);

        btnRegister.setForeground(new java.awt.Color(51, 51, 51));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("Registrarse");
        panelAuthItems.add(btnRegister);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(panelAuthItems, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel navItemContacto;
    private javax.swing.JLabel navItemInicio;
    private javax.swing.JLabel navItemNosotros;
    private javax.swing.JPanel panelAuthItems;
    private javax.swing.JPanel panelNavItems;
    // End of variables declaration//GEN-END:variables
}
