package librosfera.vista;

import javax.swing.ImageIcon;

public class App extends javax.swing.JFrame {
    //ImageIcon iconHome = new ImageIcon(this.getClass().getResource("/home.png"));

    public App() {
        initComponents();

        // Permite que la app se ejecute en pantalla maximizada
        setExtendedState(Inicio.MAXIMIZED_BOTH);
        
        // SET ICONS //
        //labelDashboard.setIcon(iconHome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSidebar = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelNavItems = new javax.swing.JPanel();
        labelDashboard = new javax.swing.JLabel();
        labelExplore = new javax.swing.JLabel();
        labelHistory = new javax.swing.JLabel();
        labelLibrary = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 728));
        setMinimumSize(new java.awt.Dimension(1400, 728));
        setPreferredSize(new java.awt.Dimension(1400, 728));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelSidebar.setBackground(new java.awt.Color(58, 33, 36));
        panelSidebar.setMaximumSize(new java.awt.Dimension(270, 728));
        panelSidebar.setMinimumSize(new java.awt.Dimension(270, 728));
        panelSidebar.setPreferredSize(new java.awt.Dimension(270, 728));
        java.awt.GridBagLayout panelSidebarLayout = new java.awt.GridBagLayout();
        panelSidebarLayout.columnWidths = new int[] {0};
        panelSidebarLayout.rowHeights = new int[] {0, 16, 0};
        panelSidebar.setLayout(panelSidebarLayout);

        labelLogo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(250, 250, 250));
        labelLogo.setText("Librosfera");
        labelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelLogo.setIconTextGap(8);
        labelLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelSidebar.add(labelLogo, gridBagConstraints);

        panelNavItems.setBackground(new java.awt.Color(58, 33, 36));
        panelNavItems.setForeground(new java.awt.Color(255, 255, 255));
        panelNavItems.setMaximumSize(new java.awt.Dimension(240, 400));
        panelNavItems.setMinimumSize(new java.awt.Dimension(240, 400));
        panelNavItems.setPreferredSize(new java.awt.Dimension(240, 400));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 24, 0, 24, 0, 24, 0};
        panelNavItems.setLayout(jPanel1Layout);

        labelDashboard.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelDashboard.setForeground(new java.awt.Color(250, 250, 250));
        labelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        labelDashboard.setText("Dashboard");
        labelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDashboard.setIconTextGap(8);
        labelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigateToDashboard(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNavItems.add(labelDashboard, gridBagConstraints);

        labelExplore.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelExplore.setForeground(new java.awt.Color(250, 250, 250));
        labelExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        labelExplore.setText("Explorar");
        labelExplore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExplore.setIconTextGap(8);
        labelExplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigateExplore(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNavItems.add(labelExplore, gridBagConstraints);

        labelHistory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelHistory.setForeground(new java.awt.Color(250, 250, 250));
        labelHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history.png"))); // NOI18N
        labelHistory.setText("Historial");
        labelHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHistory.setIconTextGap(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNavItems.add(labelHistory, gridBagConstraints);

        labelLibrary.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelLibrary.setForeground(new java.awt.Color(250, 250, 250));
        labelLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library.png"))); // NOI18N
        labelLibrary.setText("Biblioteca");
        labelLibrary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLibrary.setEnabled(false);
        labelLibrary.setIconTextGap(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNavItems.add(labelLibrary, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelSidebar.add(panelNavItems, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        getContentPane().add(panelSidebar, gridBagConstraints);

        panelContent.setBackground(new java.awt.Color(250, 250, 250));
        panelContent.setForeground(new java.awt.Color(250, 250, 250));
        panelContent.setMaximumSize(new java.awt.Dimension(1170, 728));
        panelContent.setMinimumSize(new java.awt.Dimension(1170, 728));
        panelContent.setPreferredSize(new java.awt.Dimension(1170, 728));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        getContentPane().add(panelContent, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Navegar | Vista Explorar
    private void navigateExplore(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigateExplore
 
        // Crear la vista Explorar
        Explorar vistaExplorar = new Explorar();
        
        // Establecer los tamaños
        vistaExplorar.setSize(1170, 728);
        vistaExplorar.setLocation(0, 0);
        
        // Limpiar el panel de contenido, añadir la vista y refrescarla
        panelContent.removeAll();
        panelContent.add(vistaExplorar);
        panelContent.revalidate();
        panelContent.repaint();

    }//GEN-LAST:event_navigateExplore
// Navegar | Vista Dashboard
    private void navigateToDashboard(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigateToDashboard
        // Crear la vista Dashboard
        Dashboard vistaDashboard = new Dashboard();
        
        // Establecer los tamaños
        vistaDashboard.setSize(1170, 728);
        vistaDashboard.setLocation(0, 0);
        
        // Limpiar el panel de contenido, añadir la vista y refrescarla
        panelContent.removeAll();
        panelContent.add(vistaDashboard);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_navigateToDashboard

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelExplore;
    private javax.swing.JLabel labelHistory;
    private javax.swing.JLabel labelLibrary;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelNavItems;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
