
package librosfera.vista;


public class Dashboard extends javax.swing.JPanel {
    //StarRater starRater = new StarRater();
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRating = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setLayout(new java.awt.GridBagLayout());

        panelRating.setMaximumSize(new java.awt.Dimension(300, 300));
        panelRating.setMinimumSize(new java.awt.Dimension(300, 300));
        panelRating.setName(""); // NOI18N
        panelRating.setPreferredSize(new java.awt.Dimension(300, 300));
        add(panelRating, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelRating;
    // End of variables declaration//GEN-END:variables
}
