
package librosfera.vista;


public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelViewTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setLayout(new java.awt.GridBagLayout());

        labelViewTitle.setBackground(new java.awt.Color(0, 0, 0));
        labelViewTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelViewTitle.setText("Dashboard");
        add(labelViewTitle, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelViewTitle;
    // End of variables declaration//GEN-END:variables
}
