package librosfera.vista;

public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelImg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        panelLoginForm = new javax.swing.JPanel();
        panelEmail = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        panelCreateAccount = new javax.swing.JPanel();
        labelAccountExists = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        labelLoginTitle = new javax.swing.JLabel();
        labelLoginSubtitle = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 650));
        setMinimumSize(new java.awt.Dimension(1200, 650));
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setLayout(new java.awt.GridLayout(0, 2));

        panelImg.setBackground(new java.awt.Color(255, 243, 235));
        panelImg.setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Ilustración");
        panelImg.add(jLabel1, new java.awt.GridBagConstraints());

        add(panelImg);

        panelRegister.setBackground(new java.awt.Color(250, 250, 250));
        panelRegister.setMaximumSize(new java.awt.Dimension(700, 252));
        panelRegister.setLayout(new java.awt.GridBagLayout());

        panelLoginForm.setBackground(new java.awt.Color(250, 250, 250));
        panelLoginForm.setMaximumSize(new java.awt.Dimension(550, 400));
        panelLoginForm.setMinimumSize(new java.awt.Dimension(550, 400));
        panelLoginForm.setPreferredSize(new java.awt.Dimension(550, 400));
        java.awt.GridBagLayout panelLoginFormLayout = new java.awt.GridBagLayout();
        panelLoginFormLayout.columnWidths = new int[] {0, 0, 0};
        panelLoginFormLayout.rowHeights = new int[] {0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0};
        panelLoginForm.setLayout(panelLoginFormLayout);

        panelEmail.setBackground(new java.awt.Color(250, 250, 250));
        java.awt.GridBagLayout panelEmailLayout = new java.awt.GridBagLayout();
        panelEmailLayout.columnWidths = new int[] {0};
        panelEmailLayout.rowHeights = new int[] {0, 6, 0};
        panelEmail.setLayout(panelEmailLayout);

        labelEmail.setBackground(new java.awt.Color(51, 51, 51));
        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(51, 51, 51));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmail.setText("Correo electrónico");
        labelEmail.setMaximumSize(new java.awt.Dimension(350, 16));
        labelEmail.setMinimumSize(new java.awt.Dimension(350, 16));
        labelEmail.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelEmail.add(labelEmail, gridBagConstraints);

        fieldEmail.setBackground(new java.awt.Color(238, 238, 238));
        fieldEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 1, true));
        fieldEmail.setMaximumSize(new java.awt.Dimension(400, 30));
        fieldEmail.setMinimumSize(new java.awt.Dimension(400, 30));
        fieldEmail.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelEmail.add(fieldEmail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelLoginForm.add(panelEmail, gridBagConstraints);

        panelPassword.setBackground(new java.awt.Color(250, 250, 250));
        java.awt.GridBagLayout panelPasswordLayout = new java.awt.GridBagLayout();
        panelPasswordLayout.columnWidths = new int[] {0, 0, 0};
        panelPasswordLayout.rowHeights = new int[] {0, 6, 0};
        panelPassword.setLayout(panelPasswordLayout);

        labelPassword.setBackground(new java.awt.Color(51, 51, 51));
        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(51, 51, 51));
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPassword.setText("Contraseña");
        labelPassword.setMaximumSize(new java.awt.Dimension(350, 16));
        labelPassword.setMinimumSize(new java.awt.Dimension(350, 16));
        labelPassword.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPassword.add(labelPassword, gridBagConstraints);

        fieldPassword.setBackground(new java.awt.Color(238, 238, 238));
        fieldPassword.setForeground(new java.awt.Color(51, 51, 51));
        fieldPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 1, true));
        fieldPassword.setMaximumSize(new java.awt.Dimension(400, 30));
        fieldPassword.setMinimumSize(new java.awt.Dimension(400, 30));
        fieldPassword.setPreferredSize(new java.awt.Dimension(400, 30));
        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPassword.add(fieldPassword, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelLoginForm.add(panelPassword, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(135, 23, 35));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrarse");
        btnRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setMaximumSize(new java.awt.Dimension(170, 40));
        btnRegister.setMinimumSize(new java.awt.Dimension(170, 40));
        btnRegister.setPreferredSize(new java.awt.Dimension(170, 40));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        panelLoginForm.add(btnRegister, gridBagConstraints);

        panelCreateAccount.setBackground(new java.awt.Color(250, 250, 250));
        panelCreateAccount.setMaximumSize(new java.awt.Dimension(200, 30));
        panelCreateAccount.setMinimumSize(new java.awt.Dimension(200, 30));
        panelCreateAccount.setPreferredSize(new java.awt.Dimension(200, 30));
        panelCreateAccount.setLayout(new java.awt.GridBagLayout());

        labelAccountExists.setForeground(new java.awt.Color(51, 51, 51));
        labelAccountExists.setText("¿Ya tienes una cuenta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        panelCreateAccount.add(labelAccountExists, gridBagConstraints);

        labelLogin.setForeground(new java.awt.Color(0, 51, 153));
        labelLogin.setText("Inicia sesión");
        labelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCreateAccount.add(labelLogin, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        panelLoginForm.add(panelCreateAccount, gridBagConstraints);

        panelHeader.setBackground(new java.awt.Color(250, 250, 250));
        java.awt.GridBagLayout panelHeaderLayout = new java.awt.GridBagLayout();
        panelHeaderLayout.columnWidths = new int[] {0};
        panelHeaderLayout.rowHeights = new int[] {0, 8, 0};
        panelHeader.setLayout(panelHeaderLayout);

        labelLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelLoginTitle.setForeground(new java.awt.Color(0, 0, 0));
        labelLoginTitle.setText("Registrarse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelHeader.add(labelLoginTitle, gridBagConstraints);

        labelLoginSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        labelLoginSubtitle.setText("¡Nos alegra que te unas a nuestra comunidad! ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelHeader.add(labelLoginSubtitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 32, 0);
        panelLoginForm.add(panelHeader, gridBagConstraints);

        panelRegister.add(panelLoginForm, new java.awt.GridBagConstraints());

        add(panelRegister);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    // Llevar al Home
    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        App frameHome = new App();
        frameHome.setVisible(true);
    }//GEN-LAST:event_btnRegisterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAccountExists;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLoginSubtitle;
    private javax.swing.JLabel labelLoginTitle;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelCreateAccount;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelImg;
    private javax.swing.JPanel panelLoginForm;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelRegister;
    // End of variables declaration//GEN-END:variables
}
